version: '2'
services:
  postgres:
    networks:
      custom:
        ipv4_address: 172.20.0.2
    container_name: postgres
    build:
     context: ../../containers/postgres
     args:
      - DDL_URL=${DDL_URL}
    image: hdp/postgres6
    ports:
     - "5432:5432"
    hostname: postgres

  kdc:
    networks:
      custom:
        ipv4_address: 172.20.0.3
    container_name: kdc
    image: sequenceiq/kerberos
    hostname: kdc.hdp.com
    ports:
     - "88:88"
     - "749:749"
    privileged: true
    volumes:
     - "/dev/urandom:/dev/random"
     - "/etc/krb5.conf:/etc/krb5.conf"
    environment:
      BOOTSTRAP: 0
      REALM: KDC.HDP.COM
      DOMAIN_REALM:  kdc.hdp.com
      KERB_MASTER_KEY: master
      KERB_ADMIN_USER: admin
      KERB_ADMIN_PASS: admin
      SEARCH_DOMAINS:  kdc.hdp.com


  ambari-server:
    networks:
      custom:
        ipv4_address: 172.20.0.4
    container_name: ambari-server
    build:
      context: ../../containers/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: hdp/ambari-server6
    hostname: ambari-server
    extra_hosts:
     - "kdc.hdp.com:172.20.0.3"
    ports:
     - "8080:8080"
     - "8440:8440"
     - "8441:8441"
    depends_on:
      - postgres

  master0:
    networks:
      custom:
        ipv4_address: 172.20.0.5
    container_name: master0
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/master6s
    privileged: true
    hostname: master0
    extra_hosts:
     - "kdc.hdp.com:172.20.0.3"
    ports:
     # HDFS
     - "50070:50070"
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # SPARK
     - "18080:18080"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     # MapReduce
     - "10020:10020"
     - "13562:13562"
     - "19888:19888"
     # HiveServer2
     - "9083:9083"
     - "10000:10000"
     - "9999:9999"
     # Tez
     - "12999:12999"
     - "10030:10030"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     - "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11001:11001"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"

  dn0:
    networks:
      custom:
        ipv4_address: 172.20.0.6
    container_name: dn0
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker6s
    privileged: true
    hostname: dn0
    extra_hosts:
     - "kdc.hdp.com:172.20.0.3"
    ports:
     # ZooKeeper
     - "2181"
     - "2888"
     - "3888"
     # HDFS
     - "50475"
     - "50075"
     - "50010"
     - "50020"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45455"
     # Sqoop
     - "12000"
     # Kafka
     - "6667"

  dn1:
    networks:
      custom:
        ipv4_address: 172.20.0.7
    container_name: dn1
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker6s
    privileged: true
    hostname: dn1
    extra_hosts:
     - "kdc.hdp.com:172.20.0.3"
    ports:
     # ZooKeeper
     - "2181"
     - "2888"
     - "3888"
     # HDFS
     - "50075"
     - "50475"
     - "50010"
     - "50020"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45455"
     # Sqoop
     - "12000"
     # Kafka
     - "6667"

  dn2:
    networks:
      custom:
        ipv4_address: 172.20.0.8
    container_name: dn2
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker6s
    privileged: true
    hostname: dn2
    extra_hosts:
     - "kdc.hdp.com:172.20.0.3"
    ports:
     # ZooKeeper
     - "2181"
     - "2888"
     - "3888"
     # HDFS
     - "50075"
     - "50475"
     - "50010"
     - "50020"
     # HBase
     - "16020"
     - "16030"
     # Yarn
     - "45455"
     # Sqoop
     - "12000"
     # Kafka
     - "6667"

networks:
  custom:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1
